/*
 * apimaticcalculator_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package APIMATICCalculatorClient

import(
	"apimaticcalculator_lib/configuration_pkg"
	"apimaticcalculator_lib/simplecalculator_pkg"
)


/*
 * Interface for the APIMATICCALCULATOR_IMPL
 */
type APIMATICCALCULATOR interface {
    SimpleCalculator()       simplecalculator_pkg.SIMPLECALCULATOR
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the APIMATICCALCULATOR interface returning APIMATICCALCULATOR_IMPL
 */
func NewAPIMATICCALCULATOR() APIMATICCALCULATOR {
    aPIMATICCalculatorClient := new(APIMATICCALCULATOR_IMPL)
    aPIMATICCalculatorClient.config = configuration_pkg.NewCONFIGURATION()

    return aPIMATICCalculatorClient
}
