/*
 * apimaticcalculator_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package simplecalculator_pkg

import "apimaticcalculator_lib/configuration_pkg"

/*
 * Interface for the SIMPLECALCULATOR_IMPL
 */
type SIMPLECALCULATOR interface {
    GetCalculate (*GetCalculateInput) (float64, error)
}

/*
 * Factory for the SIMPLECALCULATOR interaface returning SIMPLECALCULATOR_IMPL
 */
func NewSIMPLECALCULATOR(config configuration_pkg.CONFIGURATION) *SIMPLECALCULATOR_IMPL {
    client := new(SIMPLECALCULATOR_IMPL)
    client.config = config
    return client
}